server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:9d4dbeeb51f16d53078486d69d27654d4acfa7fb"
      snapshot: true
      repository: "https://maven.lavalink.dev/snapshots"
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TV
      - MUSIC
    oauth:
      enabled: true
      skipInitialization: false
      refreshToken: "${YOUTUBE_REFRESH_TOKEN:}"
    remoteCipher:
      url: "http://localhost:8001"
      password: ""

logging:
  level:
    root: INFO
    lavalink: INFO
